Añade las paginas de las 4 competencias
JChiquin/competencias-git pull request #20
Opened 2023-06-14 02:56 UTC by Kleiloz

Agregado

2023-06-14 19:01 UTC, JChiquin commented on competencia1.html
> -          <li class="list-group-item">Arnoldo Rodríguez</li>
Por qué eliminaste a otro participante?

2023-06-14 19:01 UTC, JChiquin commented on competencia4.html
> -          <li class="list-group-item">Arnoldo Rodríguez</li>
Por qué eliminaste a otro participante?

2023-06-14 19:02 UTC, JChiquin requested changes
Ver los comentarios acerca de código eliminado

2023-06-15 01:06 UTC, Kleiloz commented on competencia4.html
> -          <li class="list-group-item">Arnoldo Rodríguez</li>
Hola profesor, me parece extraño que lo haya eliminado puede que lo borre sin darme cuenta lo subire otra ves a ver si lo hago mal de nuevo.

2023-06-15 01:21 UTC, closed without merging